package dev.foxgirl.cminus

import net.minecraft.entity.EntityType
import net.minecraft.entity.LivingEntity
import net.minecraft.entity.passive.CatVariant
import net.minecraft.entity.passive.WolfVariants

enum class StandKind(
    val entityType: EntityType<out LivingEntity>,
    val entityInitializer: (StandEntity) -> Unit = {}
) {

    ALLAY(EntityType.ALLAY),
    ARMADILLO(EntityType.ARMADILLO),
    AXOLOTL(EntityType.AXOLOTL),
    BAT(EntityType.BAT),
    BEE(EntityType.BEE),
    BLAZE(EntityType.BLAZE),
    CAMEL(EntityType.CAMEL),
    CAT(EntityType.CAT),
    CAVE_SPIDER(EntityType.CAVE_SPIDER),
    CHICKEN(EntityType.CHICKEN),
    COD(EntityType.COD),
    COW(EntityType.COW),
    CREEPER(EntityType.CREEPER),
    DOLPHIN(EntityType.DOLPHIN),
    DONKEY(EntityType.DONKEY),
    DROWNED(EntityType.DROWNED),
    ENDERMAN(EntityType.ENDERMAN),
    ENDERMITE(EntityType.ENDERMITE),
    EVOKER(EntityType.EVOKER),
    FOX(EntityType.FOX),
    FROG(EntityType.FROG),
    GLOW_SQUID(EntityType.GLOW_SQUID),
    GOAT(EntityType.GOAT),
    HORSE(EntityType.HORSE),
    HUSK(EntityType.HUSK),
    ILLUSIONER(EntityType.ILLUSIONER),
    LLAMA(EntityType.LLAMA),
    MAGMA_CUBE(EntityType.MAGMA_CUBE),
    MOOSHROOM(EntityType.MOOSHROOM),
    MUEL(EntityType.MULE),
    OCELOT(EntityType.OCELOT),
    PANDA(EntityType.PANDA),
    PARROT(EntityType.PARROT),
    PHANTOM(EntityType.PHANTOM),
    PIG(EntityType.PIG),
    PIGLIN(EntityType.PIGLIN),
    PIGLIN_BRUTE(EntityType.PIGLIN_BRUTE),
    PILLAGER(EntityType.PILLAGER),
    PUFFERFISH(EntityType.PUFFERFISH),
    RABBIT(EntityType.RABBIT),
    SALMON(EntityType.SALMON),
    SILVERFISH(EntityType.SILVERFISH),
    SKELETON(EntityType.SKELETON),
    SKELETON_HORSE(EntityType.SKELETON_HORSE),
    SLIME(EntityType.SLIME),
    SNOW_GOLEM(EntityType.SNOW_GOLEM),
    SPIDER(EntityType.SPIDER),
    SQUID(EntityType.SQUID),
    STRAY(EntityType.STRAY),
    STRIDER(EntityType.STRIDER),
    TRADER_LLAMA(EntityType.TRADER_LLAMA),
    TURTLE(EntityType.TURTLE),
    VEX(EntityType.VEX),
    VILLAGER(EntityType.VILLAGER),
    VINDICATOR(EntityType.VINDICATOR),
    WANDERING_TRADER(EntityType.WANDERING_TRADER),
    WITCH(EntityType.WITCH),
    WITHER_SKELETON(EntityType.WITHER_SKELETON),
    WOLF(EntityType.WOLF),
    ZOMBIE(EntityType.ZOMBIE),
    ZOMBIE_VILLAGER(EntityType.ZOMBIE_VILLAGER),
    ZOMBIFIED_PIGLIN(EntityType.ZOMBIFIED_PIGLIN),

    TABBY_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.TABBY) }),
    BLACK_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.BLACK) }),
    RED_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.RED) }),
    SIAMESE_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.SIAMESE) }),
    BRITISH_SHORTHAIR_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.BRITISH_SHORTHAIR) }),
    CALICO_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.CALICO) }),
    PERSIAN_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.PERSIAN) }),
    RAGDOLL_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.RAGDOLL) }),
    WHITE_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.WHITE) }),
    JELLIE_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.JELLIE) }),
    ALL_BLACK_CAT(EntityType.CAT, { it.setVariantCat(CatVariant.ALL_BLACK) }),

    PALE_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.PALE) }),
    SPOTTED_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.SPOTTED) }),
    SNOWY_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.SNOWY) }),
    BLACK_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.BLACK) }),
    ASHEN_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.ASHEN) }),
    RUSTY_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.RUSTY) }),
    WOODS_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.WOODS) }),
    CHESTNUT_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.CHESTNUT) }),
    STRIPED_WOLF(EntityType.WOLF, { it.setVariantWolf(WolfVariants.STRIPED) }),

}
